return {
	settings_preset = "DST_CAVE", 			-- "SURVIVAL_TOGETHER", "MOD_MISSING", "SURVIVAL_TOGETHER_CLASSIC", "SURVIVAL_DEFAULT_PLUS", "COMPLETE_DARKNESS", "DST_CAVE", "DST_CAVE_PLUS", "CUSTOM_CUSTOM PRESET 1"
	worldgen_preset = "DST_CAVE", 			-- "SURVIVAL_TOGETHER", "MOD_MISSING", "SURVIVAL_TOGETHER_CLASSIC", "SURVIVAL_DEFAULT_PLUS", "COMPLETE_DARKNESS", "DST_CAVE", "DST_CAVE_PLUS", "CUSTOM_CUSTOM PRESET 1"
	override_enabled = true,
	overrides = {
	},
}